---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Run tox tests on primary host
  hosts: primary
  gather_facts: true
  become: false
  roles:
    - bindep
    - ensure-python
    - ensure-pip
    - role: ensure-tox
      become: false
      vars:
        ensure_global_symlinks: true

  tasks:

    - name: Run tox tests
      shell: |
        whereis tox || pip3 install tox --break-system-packages
        tox --version || pip3 install tox --break-system-packages
        tox -e "$TOX_ENVLIST"
      args:
        chdir: "{{ zuul.project.src_dir | default(ansible_env.HOME + '/porthole') }}"
      environment:
        TOX_ENVLIST: "{{ tox_envlist }}"
      register: tox_result

    - name: Display tox result
      debug:
        var: tox_result
      when: tox_result is defined

    - name: Check for test failures
      fail:
        msg: "Tox tests failed for environment {{ tox_envlist }}"
      when: tox_result.rc != 0